### ISSUE TITLE
There are a lot of notifications on the status bar.

### ISSUE THREAD

**Issue by luciopbrito** [Spicy-Sparks/eSound-Desktop-Releases#2]
When it opens the app, change the music, pause, or play the music. It receives a notification on the status bar. Over time, it will have many notifications. I can't access the other features related to the system. For example, I can't access the option to set or configure WiFi. I can't see the battery percentage, etc. 

So, I recorded a video using Loom to show this problem.
link: https://www.loom.com/share/c8730306e6c5408cbcb7b6734bfee749

**Comment by marf** [comment]
> When it opens the app, change the music, pause, or play the music. It receives a notification on the status bar. Over time, it will have many notifications. I can't access the other features related to the system. For example, I can't access the option to set or configure WiFi. I can't see the battery percentage, etc.
> 
> So, I recorded a video using Loom to show this problem. link: https://www.loom.com/share/c8730306e6c5408cbcb7b6734bfee749

Thank you we will take a look at this issue!

**Comment by luciopbrito** [comment]
It was solved with [2.4.2](https://github.com/Spicy-Sparks/eSound-Desktop-Releases/releases/tag/v2.4.2) version.
